### ISSUE TITLE
Code source de model

### ISSUE THREAD

**Issue by Elfilali-Taoufiq** [Cour-de-cassation/moteurNER#2]
bonjour,

merci pour ce partage, j'aimerai savoir s'il y a un code source open ou dataset pour ce travail 

et merci

**Comment by UrszulaCzerwinska** [comment]
Bonjour @Elfilali-Taoufiq,

Pour les raisons de confidentialité nous ne pouvons pas partager ni les données source, ni les modèles LM ou NER.

Les données anonymisées se trouvent sur le portail https://www.legifrance.gouv.fr/.

Pour construire un projet similaire avec vos données, vous pouvez vous baser sur le projet décrit par Etalab:

https://guides.etalab.gouv.fr/pseudonymisation/
